### ISSUE TITLE
It is not possible to set dimensions larger than the original image size

### ISSUE THREAD

**Issue by chosentwo** [HoHieuLuc/tiptap-resizable-image#6]
for example, if the original image is 200x200, when resizing, the attributes are set correctly, but the image itself returns to the original size

**Comment by HoHieuLuc** [comment]
Thanks for reporting.

**Comment by HoHieuLuc** [comment]
Fixed in [1.0.5](https://github.com/HoHieuLuc/tiptap-resizable-image/releases/tag/1.0.5)

**Comment by wilsonwg** [comment]
I encounter another problem associated with the fix committed in the 1.0.5.

In 1.0.4 the style was:

.image-component img[data-keep-ratio]:not([data-keep-ratio='false']) {
  width: 100%;
  height: auto;
  object-fit: contain;
}

In 1.0.5 the style changed to:

.image-component img[data-keep-ratio]:not([data-keep-ratio='false']) {
  object-fit: contain;
}

There is a problem when removing the top two lines.

In 1.0.4, if the editor's width is greater than the image's width, everything works normally.
And if the editor's width becomes smaller than the image's width, the image would scale down and maintain the proportion and fit into the editor,

After removing the two lines, when the editor's width becomes smaller than the image's width, the image would overflow the editor's boundary.

I don't know what's the best solution to this issue, as another person has mentioned another issue.

Perhaps the most safe solution is not to provide image's width by default?

**Comment by wilsonwg** [comment]
After asking AI for the solution and also made some random wacky experiments, I seem to have found the solution by changing the style as below:

.image-component img[data-keep-ratio]:not([data-keep-ratio='false']) {
  width: 100%;
  max-width: 100%;
  object-fit: contain;
}

So far in my tests, the image is able resize perfectly and would not overflow the editor if the editor's width become smaller.

I'm not a CSS expert and don't know why this works, but it just works.

I'm still testing to see if there are other issues associated with this style.

**Comment by HoHieuLuc** [comment]
> I encounter another problem associated with the fix committed in the 1.0.5.
> 
> In 1.0.4 the style was:
> 
> .image-component img[data-keep-ratio]:not([data-keep-ratio='false']) { width: 100%; height: auto; object-fit: contain; }
> 
> In 1.0.5 the style changed to:
> 
> .image-component img[data-keep-ratio]:not([data-keep-ratio='false']) { object-fit: contain; }
> 
> There is a problem when removing the top two lines.
> 
> In 1.0.4, if the editor's width is greater than the image's width, everything works normally. And if the editor's width becomes smaller than the image's width, the image would scale down and maintain the proportion and fit into the editor,
> 
> After removing the two lines, when the editor's width becomes smaller than the image's width, the image would overflow the editor's boundary.
> 
> I don't know what's the best solution to this issue, as another person has mentioned another issue.
> 
> Perhaps the most safe solution is not to provide image's width by default?

Thanks for reporting. I’m not sure how to fix it without reintroducing the previous issue. As a temporary solution, you can add the old CSS back to your codebase.

**Comment by wilsonwg** [comment]
From my code experiments, it seems that the situation can be improved by using the style below:

`.image-component img[data-keep-ratio]:not([data-keep-ratio='false']) {`
`  width: 100%;`
`  object-fit: contain;`
`}`


The "height: auto;" is removed. By using this setting, the image would not bounce back to the original size when it is enlarged than it's original size. And when the editor's width becomes smaller than the image's width, the image would fit into the editor. The only problem now is that when the editor's width is smaller the image's width, the resizer would add a large vertical white spaces around the image. This is the only problem that I have encountered so far, but I'm not sure if this issue can be resolved or not.

**Comment by wilsonwg** [comment]
Just a further note, this trick would not work if tailwind is installed. This is because tailwind has a global setting with img height being set to auto.
